services:
  - type: web
    name: url-shortener-api
    runtime: node
    rootDir: backend
    buildCommand: npm install && npm run build && npx prisma generate && npx prisma migrate deploy
    startCommand: node dist/src/app.js
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 3001